"""Supervisor Agent.

Receives a natural-language objective and:
  1. PLANS — LLM call producing a typed SupervisorPlan (list of subtasks).
  2. EXECUTES — dispatches each subtask through the agent registry. On failure,
     retries with a *modified* instruction generated by another LLM call
     (Task 1 hard requirement #2). After N retries, escalates and continues with
     remaining subtasks (graceful degradation; Task 1 hard requirement #4).
  3. SYNTHESISES — final LLM call that turns the structured results into a
     natural-language answer for the user. If the plan requested a draft_report,
     the Report Agent's output is included in the synthesis.

Why this shape (vs. one big prompt that calls functions): each specialist agent
runs its own LLM call with its own system prompt and validates its own output.
The supervisor only routes — it does not know HOW inventory or production reason.
"""
from __future__ import annotations

import os
from typing import Any

from shared.agent_base import Agent
from shared.intents import (
    DraftReportInput,
    PlannedSubtask,
    ReportSectionInput,
    SupervisorPlan,
)
from shared.messages import AgentError, AgentMessage, MessageMetadata
from shared.trace import trace

from .report import ReportAgent

MAX_RETRIES = int(os.getenv("SUPERVISOR_MAX_RETRIES", "1"))

PLANNER_SYSTEM = """You are the Supervisor of a manufacturing-operations agent team.
Decompose the user's objective into the MINIMUM set of subtasks needed.

Available agents and intents (use ONLY these):
- inventory.check_stock(materials: list[str])
- production.check_schedule(date_range: [start_iso, end_iso])
- production.place_order(material: str, quantity: number, supplier_id: str, urgency: 'low'|'standard'|'high'|'critical')
- report.draft_report(title: str, sections: list[{heading, data}])

Known materials: rose_oil, glycerin, beeswax, vitamin_e, packaging_30ml, packaging_50ml.
Lines: line_1, line_2, line_3.
Suppliers: SUP-001, SUP-002, SUP-003.

ROUTING RULES (follow exactly):
- A question ONLY about stock/materials/inventory -> ONLY inventory.check_stock.
  Do NOT call production. Do NOT include a report.
- A question ONLY about production/bottlenecks/schedule/lines/orders -> ONLY production.check_schedule.
  Do NOT call inventory. Do NOT include a report.
- A request for a "briefing", "summary", "report", "morning report", or any
  explicit multi-topic overview -> inventory + production + report.
- An explicit instruction to PLACE / CREATE / ISSUE / RAISE a purchase order
  (verbs like "order", "buy", "raise a PO") -> ONLY production.place_order with
  the parsed material, quantity, supplier_id, urgency. Do NOT also call
  check_stock or check_schedule unless the user explicitly asked for them too.

Examples:
- "Are we low on glycerin?"                  -> [inventory], needs_report=false
- "What's blocking production today?"        -> [production.check_schedule], needs_report=false
- "What's blocked on line 2?"                -> [production.check_schedule], needs_report=false
- "Give me the morning briefing"             -> [inventory, production.check_schedule], needs_report=true
- "Summarise today's operations"             -> [inventory, production.check_schedule], needs_report=true
- "Order 300 units of glycerin from SUP-002, standard urgency"
                                              -> [production.place_order], needs_report=false
- "Place a high-urgency PO for 1500 units of glycerin with SUP-002"
                                              -> [production.place_order], needs_report=false

Other rules:
- needs_report MUST be false unless the user explicitly asked for a briefing/report/summary.
- Do NOT pre-populate report.draft_report sections; the supervisor fills them at synthesis time.
- If the user did not specify which materials for a check_stock, include the full known materials list.
- A question being "complex" or "important" is NOT a reason to call extra agents.
- For place_order, copy material/quantity/supplier_id/urgency exactly as the user stated. Do NOT infer
  values they did not give. If urgency is unspecified, use "standard".
- For check_schedule, date_range MUST be a list of two ISO calendar dates in
  YYYY-MM-DD format. NEVER use natural-language placeholders like "today" or
  "today's start". If the user did not specify a range, default to [today, today]
  using the UTC date provided in the user message.
"""

SYNTHESIS_SYSTEM = """You are the Supervisor producing the final answer for the user.
Use ONLY the data in the structured results. Do not invent numbers, statuses, or
materials. If a subtask failed, say so plainly. Keep the answer concise."""

RETRY_FIXUP_SYSTEM = """You are the Supervisor. A subordinate agent failed.
Produce a modified payload that addresses the error. Output JSON only."""


class SupervisorAgent(Agent):
    name = "supervisor"
    prompt_version = "sup.v1"

    def __init__(
        self,
        llm=None,
        registry: dict[str, Agent] | None = None,
        max_retries: int = MAX_RETRIES,
    ):
        super().__init__(llm=llm)
        self.registry = registry or {}
        self.max_retries = max_retries

    # ---- public entry: run an objective end-to-end -------------------------

    def run(self, objective: str, trace_id: str) -> dict[str, Any]:
        """Top-level. Not routed through `handle()` because this is the entrypoint.

        Returns a dict with `status` in {'ok', 'needs_human'}. On 'needs_human',
        the run is persisted to `paused_runs` and `pending` lists the
        confirmation_ids the caller must approve before calling `resume(trace_id)`.
        """
        with trace(
            self.name,
            "agent",
            trace_id=trace_id,
            prompt_version=self.prompt_version,
            input_payload={"objective": objective},
        ) as rec:
            plan = self._plan(objective, trace_id, rec.span_id)
            results = self._execute(plan, trace_id, rec.span_id)

            # If any subtask is paused awaiting human approval, persist + return
            # early. The supervisor does NOT synthesise a partial answer — the
            # caller must approve and call resume() (which replays from scratch
            # with idempotency handling the dedup).
            pending = [r for r in results if r["status"] == "needs_human"]
            if pending:
                self._persist_paused(trace_id, objective)
                rec.output_payload = {
                    "status": "needs_human",
                    "pending_confirmation_ids": [
                        (r.get("payload") or {}).get("confirmation_id") for r in pending
                    ],
                }
                return {
                    "status": "needs_human",
                    "trace_id": trace_id,
                    "objective": objective,
                    "plan": plan.model_dump(),
                    "results": results,
                    "pending": [
                        {
                            "agent": r["agent"],
                            "intent": r["intent"],
                            "confirmation_id": (r.get("payload") or {}).get("confirmation_id"),
                            "reason": (r.get("payload") or {}).get("reason"),
                        }
                        for r in pending
                    ],
                }

            briefing = self._maybe_report(plan, results, trace_id, rec.span_id)
            answer = self._synthesise(objective, results, briefing, trace_id, rec.span_id)

            rec.output_payload = {
                "status": "ok",
                "answer": answer[:500],
                "subtasks_called": [s.agent for s in plan.subtasks],
                "subtask_status": {
                    s.agent: results[i]["status"] for i, s in enumerate(plan.subtasks)
                },
            }
            return {
                "status": "ok",
                "answer": answer,
                "plan": plan.model_dump(),
                "results": results,
                "briefing": briefing.model_dump() if briefing else None,
            }

    # ---- resume after out-of-band approval --------------------------------

    def resume(self, trace_id: str) -> dict[str, Any]:
        """Re-run the previously-paused objective. Idempotent tools dedupe the
        already-done work; approved confirmations let the previously-paused
        tool execute."""
        from shared.db import get_conn

        conn = get_conn()
        try:
            row = conn.execute(
                "SELECT objective, status FROM paused_runs WHERE trace_id = ?",
                (trace_id,),
            ).fetchone()
        finally:
            conn.close()
        if not row:
            return {"status": "error", "error": f"no paused run for trace_id {trace_id}"}
        if row["status"] == "resumed":
            return {"status": "error", "error": f"trace_id {trace_id} already resumed"}

        result = self.run(row["objective"], trace_id=trace_id)
        if result.get("status") == "ok":
            conn = get_conn()
            try:
                conn.execute(
                    """UPDATE paused_runs SET resumed_at = datetime('now'), status = 'resumed'
                       WHERE trace_id = ?""",
                    (trace_id,),
                )
                conn.commit()
            finally:
                conn.close()
        return result

    def _persist_paused(self, trace_id: str, objective: str) -> None:
        from shared.db import get_conn

        conn = get_conn()
        try:
            conn.execute(
                """INSERT OR REPLACE INTO paused_runs (trace_id, objective, paused_at, status)
                   VALUES (?, ?, datetime('now'), 'paused')""",
                (trace_id, objective),
            )
            conn.commit()
        finally:
            conn.close()

    # ---- internals ---------------------------------------------------------

    def _plan(self, objective: str, trace_id: str, parent_span_id: str) -> SupervisorPlan:
        from datetime import datetime, timezone
        today = datetime.now(timezone.utc).date().isoformat()
        plan, _ = self.llm.complete_json(
            system=PLANNER_SYSTEM,
            user=f"Today's UTC date is {today}.\n\nObjective: {objective}",
            schema=SupervisorPlan,
            trace_id=trace_id,
            parent_span_id=parent_span_id,
            prompt_version=self.prompt_version,
        )
        # Defensive: drop the report subtask from the planner output here — we
        # add it back ourselves after the specialists run, with the right data.
        plan.subtasks = [s for s in plan.subtasks if s.intent != "draft_report"]
        return plan

    def _execute(
        self, plan: SupervisorPlan, trace_id: str, parent_span_id: str
    ) -> list[dict[str, Any]]:
        results: list[dict[str, Any]] = []
        for subtask in plan.subtasks:
            outcome = self._dispatch_with_retry(subtask, trace_id, parent_span_id)
            results.append(outcome)
        return results

    def _dispatch_with_retry(
        self, subtask: PlannedSubtask, trace_id: str, parent_span_id: str
    ) -> dict[str, Any]:
        agent = self.registry.get(subtask.agent)
        if agent is None:
            return {
                "agent": subtask.agent,
                "intent": subtask.intent,
                "status": "error",
                "payload": None,
                "error": {"error_class": "unknown_agent", "message": f"No agent: {subtask.agent}"},
                "attempts": 0,
            }

        payload = dict(subtask.payload)
        last_error: AgentError | None = None
        for attempt in range(self.max_retries + 1):
            msg = AgentMessage(
                trace_id=trace_id,
                parent_span_id=parent_span_id,
                from_agent="supervisor",
                to_agent=subtask.agent,
                intent=subtask.intent,  # type: ignore[arg-type]
                payload=payload,
                attempts=attempt,
            )
            reply = agent.handle(msg)
            if reply.status == "success":
                return {
                    "agent": subtask.agent,
                    "intent": subtask.intent,
                    "status": "success",
                    "payload": reply.payload,
                    "attempts": attempt + 1,
                    "metadata": reply.metadata.model_dump(),
                }
            if reply.status == "needs_human":
                # Do NOT retry. Propagate as-is — supervisor.run() persists the
                # paused run and short-circuits the synthesis.
                return {
                    "agent": subtask.agent,
                    "intent": subtask.intent,
                    "status": "needs_human",
                    "payload": reply.payload,
                    "attempts": attempt + 1,
                }
            last_error = reply.error
            if not reply.error or not reply.error.retryable or attempt == self.max_retries:
                break
            # Generate a modified payload to address the error.
            payload = self._revise_payload(subtask, payload, reply.error, trace_id, parent_span_id)

        # Escalate after retries exhausted.
        return {
            "agent": subtask.agent,
            "intent": subtask.intent,
            "status": "escalated",
            "payload": None,
            "error": last_error.model_dump() if last_error else None,
            "attempts": self.max_retries + 1,
        }

    def _revise_payload(
        self,
        subtask: PlannedSubtask,
        previous_payload: dict,
        error: AgentError,
        trace_id: str,
        parent_span_id: str,
    ) -> dict:
        """Ask the LLM for a corrected payload given the failure reason."""
        from pydantic import BaseModel

        class _Revised(BaseModel):
            payload: dict

        user = (
            f"Agent: {subtask.agent}\n"
            f"Intent: {subtask.intent}\n"
            f"Previous payload: {previous_payload}\n"
            f"Error: [{error.error_class}] {error.message}\n\n"
            "Return a corrected payload. Keep the same intent. If the previous payload "
            "was structurally fine and the failure was transient, return the same payload."
        )
        try:
            revised, _ = self.llm.complete_json(
                system=RETRY_FIXUP_SYSTEM,
                user=user,
                schema=_Revised,
                trace_id=trace_id,
                parent_span_id=parent_span_id,
                prompt_version=self.prompt_version,
            )
            return revised.payload or previous_payload
        except Exception:
            # If even the retry-planner LLM fails, fall back to the original payload.
            return previous_payload

    def _maybe_report(
        self,
        plan: SupervisorPlan,
        results: list[dict[str, Any]],
        trace_id: str,
        parent_span_id: str,
    ):
        if not plan.needs_report:
            return None
        report_agent = self.registry.get("report")
        if not isinstance(report_agent, ReportAgent):
            return None

        sections = [
            ReportSectionInput(heading=r["agent"], data=r.get("payload") or {"error": r.get("error")})
            for r in results
        ]
        payload = DraftReportInput(
            title="Operations briefing",
            sections=sections,
        ).model_dump()

        msg = AgentMessage(
            trace_id=trace_id,
            parent_span_id=parent_span_id,
            from_agent="supervisor",
            to_agent="report",
            intent="draft_report",
            payload=payload,
        )
        reply = report_agent.handle(msg)
        if reply.status != "success":
            return None
        from shared.intents import DraftReportOutput
        return DraftReportOutput.model_validate(reply.payload)

    def _synthesise(
        self,
        objective: str,
        results: list[dict[str, Any]],
        briefing,
        trace_id: str,
        parent_span_id: str,
    ) -> str:
        results_summary = "\n".join(
            f"- {r['agent']}.{r['intent']} -> {r['status']} "
            f"(attempts={r['attempts']}): "
            f"{str(r.get('payload') or r.get('error'))[:600]}"
            for r in results
        ) or "(no subtasks executed)"

        briefing_block = ""
        if briefing is not None:
            briefing_block = f"\n\nDraft briefing produced by Report Agent:\n{briefing.model_dump()}"

        user = (
            f"Original objective: {objective}\n\n"
            f"Subtask results:\n{results_summary}{briefing_block}\n\n"
            "Write the final answer for the user."
        )
        resp = self.llm.complete(
            system=SYNTHESIS_SYSTEM,
            user=user,
            trace_id=trace_id,
            parent_span_id=parent_span_id,
            prompt_version=self.prompt_version,
        )
        return resp.content.strip()

    # The supervisor is not invoked via AgentMessage in this task — `run()` is
    # the entrypoint. Keep `_handle` defined so the abstract contract is met.
    def _handle(self, message: AgentMessage, *, parent_span_id: str) -> AgentMessage:
        result = self.run(objective=message.payload.get("objective", ""), trace_id=message.trace_id)
        return message.reply(
            status="success",
            payload={"answer": result["answer"]},
            metadata=MessageMetadata(prompt_version=self.prompt_version),
        )
